baseurl = "https://r-aleatorio.com/"
title = "Aleatório"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusshortname = "r-aleatorio-com" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
DefaultContentLanguage = "pt"
# Set to "hide" or "show" all codes by default
codefolding_show = "hide"

[Author]
name = "Henrique de Assunção"
bio = "Cientista de dados brasileiro, mestre em economia. Gosto de economia, filosofia, teologia, arte, cultura, jogos..."
avatar = "img/henrique.jpg"


[Params]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "dados"]
subtitle = "Site do Henrique" # Subtitle of your site
mainSections = ["blog", "sobre"]
description = "Blog pessoal do Henrique sobre qualquer coisa" # Description of your site
opengraph = true
twitter_cards = false
readmore = true # Show "Read more" button in list if true
authorbox = true
post_navigation = true
post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
home = "right"   # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
