---
title: Economia e Moralidade\: Market Reasoning as Moral Reasoning
author: Henrique de Mello de Assunção
date: '2019-08-25'
categories:
  - Pesquisa
tags:
  - Resenha
  - Artigo
  - Economia
  - Moralidade
slug: filler-episode-impact-on-naruto
bibliography: [bibliografia.bib]
---

# Economia e Moralidade

Esta postagem é uma resenha do artigo *Market reasoning as moral reasoning: why economists should re-engage with political philosophy* [@sandel2013market]. O artigo trata de questões de moralidade dentro da ciência econômica, mais especificamente, como economistas tratam de questões éticas e morais dentro de seus escritos e de sua pesquisa. Segundo o autor, economistas tratam a ciência econômica como um ciência neutra, sem algo normativo a falar sobre debates morais, embora constantemente façam proposições e suposições de conteúdo ético e moral. Desta forma, a economia, enquanto conhecimento, é prejudicada por não tratar explicitamente de seus axiomas éticos e morais. Portanto, o autor propõe que haja um debate ético e moral dentro da ciência econômica voltando a suas origens dentro da filosofia prática.

## Opinião

O artigo apresenta um problema muito interessante e pouco falado. Os valores morais e éticos apresentados na economia. Uma visão comum de um economista é pensar em sistemas com agentes racionais, não como bons agentes, ou agentes maus. A crítica proposta é dizer que esta visão, e outras visões tradicionais prevalentes entre cientistas econômicos[^1], limita o pensamento econômico tanto em escopo como em profundidade. 

[^1]: O caso de virtude como um recurso escasso apresentado no artigo é um exemplo interessante de um visão presente na ciência econômica.

É uma boa leitura recheada de anedotas interessantes que devem divertir e instigar a leitura de economistas e interessados na ciência econômica. Acredito que o artigo pode interessar o público geral com algum conhecimento de ciência econômica (excluindo no caso pessoas que acham que economia refere-se apenas a medir o PIB e mercado financeiro). Embora acredite que este artigo deva interessar o público geral, pessoas interessadas em economia institucional, complexidade ou história econômica devem gostar deste artigo devem apreciar especialmente o texto. 


## Textos relacionados

O material mais parecido a este artigo possível é o livro escrito pelo próprio Sandel sobre o assunto, [O que o dinheiro não compra](https://www.amazon.com.br/que-dinheiro-n%C3%A3o-compra/dp/8520011489/ref=sr_1_1?hvadid=72018109570228&hvbmt=be&hvdev=c&hvqmt=e&keywords=o+que+o+dinheiro+n%C3%A3o+compra&qid=1569796330&sr=8-1). O que o dinheiro não compra é um livro que discorre mais extensamente sobre o tópico trazendo vários exemplos presente neste artigo.

Uma autora que trabalha muito bem este tema é [Deirdre McCloskey](http://www.deirdremccloskey.com/). Uma ótima escritora, recomendo o texto [Not institutions, but ethics and religion](http://christianeconomists.org/wp-content/uploads/2017/02/2016-Fall-McCloskey.pdf). McCloaskey é uma autora muito interessante que explora novas ideias e perspectivas com muito clareza e erudição.

# Referências

