---
title: "Criação de pacote em R, parte 2: Testes"
author: Henrique de Mello de Assunção
date: '2020-07-03'
thumbnail:
categories:
  - R
tags:
  - R
  - Simulação
  - Reprodutibilidade
---

# Testes

Essa é a segunda parte de uma série que estou escrevendo sobre escrever pacotes no R. Nesta parte vou usar o pacote [_tinytest_](https://github.com/markvanderloo/tinytest) para os exemplos. O exemplo usado nesta postagem é a versão traduzida do exemplo usado no site do github do pacote.

A minha principal surpresa quando comecei a escrever um pacote foi a importância de testes na produção de um pacote. É incrível a quantidade de vezes que alguma alteração ou boa ideia no decorrer de um projeto acaba estragando vários partes anteriores do mesmo projeto. Quando isso ocorre começa um trabalho investigativo para se descobrir o que está acontecendo de errado. Essa situação pode ser simples ou muito complicada, atrapalhando bastante a diversão de se construir um pacote.

Uma solução para este problema, e outros é a construção de testes automatizados durante o processo de escrita do pacote. Estes testes permitem construir vários cenários idealizados de funcionamento correto do pacote e simplificar os casos de falhas, tornando o processo investigativo descrito anteriormente focado nos problemas revelados pelos testes.

## Testes automatizados no R

A construção de testes automáticos no R é a construção de um _script_ com várias proposições lógicas a serem avaliadas pelo computador. A ideia é que se tudo está certo todas as proposições vão dão dar uma valor previamente estabelecido normalmente `r TRUE`. Caso alguma proposiçao dê o valor incorreto o teste falha e você sabe a razão da falha, ou pelo menos a situação específica que não está mais funcionando.

> Uma ideia de se imaginar isso é considerar como se você estivesse escrevendo um livro. Os testes dizem se o capítulo que você está escrevendo fazem sentido com os capítulos ja escritos.

Com isso pode-se escrever muitos testes e se realiza-los ao longo do processo de escrita do pacote. Com isso, toda vez que se roda os testes pode-se saber se alguma coisa _quebrou_ ao longo do caminho, entender o problema e começar o processo de conserto com uma ideia bem mais clara do que aconteceu de errado. 

Isso é **extremamente importante** e meu maior arrependimento ao escrever um pacote foi não começar a escrever testes durante o processo de testagem. É mais fácil se construir testes durante o processo do que retornar, dias, semanas ou meses depois e ir escrevendo testes de funções que não estão mais _frescas_.

## Outros benefícios

Outro benefício de se escrever testes é estudar melhor o que se está escrevendo. Esse processo reflexivo faz com que se entenda melhor o código, o que ele deveria fazer, qual são possíveis cenários de falha. Isso auxilia no desenvolvimento do projeto.

Uma outra vantagem é a felicidade de se ver todos o seu projeto passando em todos os teste escritos. É uma grande alegria em alguns momentos e um pequeno incentivo em outros. Essa alegria pode ser a diferença em se terminar um processo.

## Exemplo de teste

Um exemplo de teste em R pode ser visto abaixo. Cria-se duas funções simples, a primeira está correta enquanto a segunda está incorreta. A primeira é para adicionar um a um valor númerico dado e a segunda supostamente subtrairia-se um a um valor númerico dado, porém está subtraindo dois. O script apresenta dois testes simples em que se escreve o resultado esperado da função dado um parâmetro.

```{r}
adiciona_um <- function(x) x + 1
subtrai_um <- function(x) x - 2

#  Esse teste vai passar
tinytest::expect_equal(adiciona_um(1), 2 )

# Esse teste vai falhar
tinytest::expect_equal(subtrai_um(2), 1 ) 
```

Como era esperado a primeira função mostra que o teste foi bem sucedido enquanto a segunda apresenta uma falha. O exemplo é trivial, e completamente copiado do site do pacote [_tinytest_](https://github.com/markvanderloo/tinytest), mas em funções mais complicadas e maiores os testes se mostram ainda mais importantes devido a dificuldade de se abstrair todas as operações.

## Pacotes para testes

Eu conheço três pacotes para testes em R, que são:

* [_tinytest_](https://github.com/markvanderloo/tinytest);
* [_tinytest_](https://testthat.r-lib.org/);
* [_tinytit_](https://github.com/yihui/testit).

